#server.port=9292

#spring.datasource.url=jdbc:mysql://localhost:3306/asia
#spring.datasource.username=root
#spring.datasource.password=Venkat@07
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true

server:
    port: 9292
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
